config/routes.rb
Rails.application.routes.draw do

  resources :enrollments
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    resources :courses do
      resources :lessons
    end
    root 'static_pages#landing_pages'
    get 'static_pages/activity'
    get 'privacy_policy', to: 'static_pages#privacy_policy'
    resources :users, only: [:index, :edit, :update, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user

  validates :user, :course, presence: true

  validates_uniqueness_of :user_id, scope: :course_id
  validates_uniqueness_of :course_id, scope: :user_id

  validate :cant_subscribe_to_own_course

  def to_s
    user.username + " " + course.to_s
  end

  protected

  def cant_subscribe_to_own_course
    if self.new_record?
      if self.user_id.present? && self.course_id.present?
        if self.user_id == self.course.user_id
          errors.add(:base, "You can't subscribe to your own course")
        end
      end
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]

  def index
    @enrollments = Enrollment.all
  end

  def show
  end

  def new
    @enrollment = Enrollment.new
  end

  def edit
  end

  def create
    @enrollment = Enrollment.new(enrollment_params)
    @enrollment.price = @enrollment.course.price

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    def enrollment_params
      params.require(:enrollment).permit(:course_id, :user_id, :rating, :review)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :course
    = f.association :user, label_method: :username
    = f.input :rating
    = f.input :review

  .form-actions
    = f.button :submit

app/views/enrollments/edit.html.haml
- content_for :title, "#{t('edit')} #{@enrollment.to_s}"

.card
  .card-header
    %h3
      .fa.fa-lock-open
      Editing enrollment
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show', @enrollment
    \|
    = link_to 'Back', enrollments_path

app/views/enrollments/index.html.haml
- content_for :title, "#{t('enrollments')}"

%h3
  .text-center
    = t('enrollments')
    .badge.badge-info
      = @enrollments.count
%p

%h1 Listing enrollments
.table-responsive
  %table.table.table-striped.table-bordered.table-sm
    %thead
      %tr
        %th Course
        %th User
        %th Rating
        %th Review
        %th Price
        %th
        %th
        %th

    %tbody
      - @enrollments.each do |enrollment|
        %tr
          %td= enrollment.course
          %td= enrollment.user.username
          %td= enrollment.rating
          %td= enrollment.review
          %td= number_to_currency(enrollment.price)
          %td= link_to 'Show', enrollment
          %td= link_to 'Edit', edit_enrollment_path(enrollment)
          %td= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Enrollment', new_enrollment_path

app/views/enrollments/new.html.haml
- content_for :title, "#{t('new')} #{t('enrollment')}"

.card
  .card-header
    %h3
      .fa.fa-lock-open
      New enrollment
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back', enrollments_path

app/views/enrollments/show.html.haml
%p#notice= notice

%p
  %b Course:
  = @enrollment.course
%p
  %b User:
  = @enrollment.user
%p
  %b Rating:
  = @enrollment.rating
%p
  %b Review:
  = @enrollment.review
%p
  %b Price:
  = @enrollment.price

= link_to 'Edit', edit_enrollment_path(@enrollment)
\|
= link_to 'Back', enrollments_path