config/routes.rb
Rails.application.routes.draw do

  resources :enrollments
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    resources :courses do
      resources :lessons
    end
    root 'static_pages#landing_pages'
    get 'static_pages/activity'
    get 'privacy_policy', to: 'static_pages#privacy_policy'
    resources :users, only: [:index, :edit, :update, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%hr
%footer
  .container
    .row
      .col-md-4
        Copyright
        ©
        = Time.now.year
        CoursePlatform Sp. z o.o.
        .row
        .fa.fa-envelope
        = mail_to 'asdasd@gmail.com'
        .row
      .col-md-4
        Privacy policy
        .row
        Terms and conditions
      .col-md-4
        About us
        .row
        = link_to 'Teach on CoursePlatform', new_course_path
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid
    %a.navbar-brand{:href => "/"}
      /= image_tag 'logo.png', size: '20x20', alt: "logo", class: 'rounded'
      .fa.fa-graduation-cap
    Corsego
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      - if current_user
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
            = link_to root_path, class: 'nav-link' do
              .fa.fa-home
              Home
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
            = link_to courses_path, class: 'nav-link' do
              .fa.fa-graduation-cap
              Courses
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
            = link_to new_course_path, class: 'nav-link' do
              .fa.fa-plus
              New Course
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
            = link_to users_path, class: 'nav-link' do
              .fa.fa-users
              Users
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
            = link_to enrollments_path, class: 'nav-link' do
              .fa.fa-lock-open
              = t 'enrollments'
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(static_pages_activity_path)}"}
            = link_to static_pages_activity_path, class: 'nav-link' do
              .fa.fa-bell
              Activity
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(static_pages_activity_path)}"}
            = link_to root_path(locale: :tr), class: 'nav-link' do
              .fa.fa-bell
              Turkish
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(static_pages_activity_path)}"}
            = link_to root_path(locale: :en), class: 'nav-link' do
              .fa.fa-bell
              English

          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              %b= current_user.email
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              %li
                %a.dropdown-item{:href => edit_user_registration_path }
                  .fa.fa-cog
                  %b Account settings
              %li
                %a.dropdown-item{:href => destroy_user_session_path}
                  .fa.fa-sign-out-alt
                  %b Sign out

        = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
          .input-group
            = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
            %span.input-group-append
              %button.btn.btn-primary.btn-sm{:type => "submit"}
                %span.fa.fa-search{"aria-hidden" => "true"}
      - else
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_user_registration_path)}"}
            = link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_user_session_path)}"}
            = link_to 'Login I', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    /%title Rubygems
    %title
      = content_for?(:title) ? yield(:title) : "Rubygems"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      %p
      = yield
    %br
      .bg-dark.text-white
      = render 'layouts/footer'